// <auto-generated />
namespace PetService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m2m2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m2m2));
        
        string IMigrationMetadata.Id
        {
            get { return "201606030659569_m2m2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
